export const categories = [
  {
    title: "Supervised Learning",
    description: `
**Definition:** A type of machine learning where the model is trained on a labeled dataset — meaning each input has a known correct output.  

**Goal:** Learn the mapping from inputs to outputs for prediction or classification.  

**Examples:** Predicting house prices, spam email detection, medical diagnosis.  

**Key Algorithms:** Linear Regression, Logistic Regression, Decision Trees, Random Forests, Support Vector Machines (SVM), Gradient Boosting.  
    `,
    items: [
      { name: "Linear Regression", slug: "linear-regression", description: "Predicts a continuous output based on input features using a linear relationship.", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec.", src: "/gifs/lr.gif" },
      { name: "Logistic Regression", slug: "logistic-regression", description: "Predicts a binary outcome using a logistic function.", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec.", src: "/gifs/lr.gif" },
      { name: "Decision Trees", slug: "decision-trees", description: "Splits data into branches to make decisions based on features.", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec.", src: "/gifs/lr.gif" },
      { name: "Random Forest", slug: "random-forest", description: "Ensemble of decision trees to improve prediction accuracy.", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec.", src: "/gifs/lr.gif" },
      { name: "Support Vector Machines (SVM)", slug: "svm", description: "Finds the hyperplane that best separates data into classes.", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec.", src: "/gifs/lr.gif" },
      { name: "Gradient Boosting", slug: "gradient-boosting", description: "Boosts weak learners iteratively to form a strong model.", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec.", src: "/gifs/lr.gif" },
      { name: "AdaBoost", slug: "adaboost", description: "Adaptive boosting algorithm to combine weak classifiers.", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec.", src: "/gifs/lr.gif" },
      { name: "XGBoost", slug: "xgboost", description: "Optimized gradient boosting library for performance.", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec.", src: "/gifs/lr.gif" },
      { name: "LightGBM", slug: "lightgbm", description: "Gradient boosting framework with faster training speed.", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec.", src: "/gifs/lr.gif" },
      { name: "CatBoost", slug: "catboost", description: "Gradient boosting algorithm that handles categorical features.", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec.", src: "/gifs/lr.gif" },
      { name: "Ridge Regression", slug: "ridge-regression", description: "Linear regression with L2 regularization.", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec.", src: "/gifs/lr.gif" },
      { name: "Lasso Regression", slug: "lasso-regression", description: "Linear regression with L1 regularization for feature selection.", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec.", src: "/gifs/lr.gif" },
    ],
  },
  {
    title: "Unsupervised Learning",
    description: `
**Definition:** A type of machine learning where models work on unlabeled data, trying to find hidden structures or groupings without predefined answers.  

**Goal:** Discover patterns, clusters, or reduce dimensions for better understanding of data.  

**Examples:** Customer segmentation, market basket analysis, gene expression analysis.  

**Key Algorithms:** K-Means, Hierarchical Clustering, DBSCAN, PCA, t-SNE, UMAP, ICA.  
    `,
    items: [
      { name: "K-Means Clustering", slug: "kmeans", description: "Partitions data into k clusters based on similarity.", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec.", src: "/gifs/lr.gif" },
      { name: "Hierarchical Clustering", slug: "hierarchical-clustering", description: "Creates a tree of clusters from data points.", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec.", src: "/gifs/lr.gif" },
      { name: "DBSCAN", slug: "dbscan", description: "Density-based clustering for discovering arbitrary-shaped clusters.", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec.", src: "/gifs/lr.gif" },
      { name: "Principal Component Analysis (PCA)", slug: "pca", description: "Reduces dimensionality while preserving variance.", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec.", src: "/gifs/lr.gif" },
      { name: "t-SNE", slug: "tsne", description: "Non-linear dimensionality reduction for visualization.", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec.", src: "/gifs/lr.gif" },
      { name: "UMAP", slug: "umap", description: "Uniform Manifold Approximation for visualization and embedding.", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec.", src: "/gifs/lr.gif" },
      { name: "Independent Component Analysis (ICA)", slug: "ica", description: "Separates a multivariate signal into independent sources.", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec.", src: "/gifs/lr.gif" },
    ],
  },
  {
    title: "Reinforcement Learning",
    description: `
**Definition:** A learning paradigm where an agent interacts with an environment, takes actions, and learns from feedback in the form of rewards or penalties.  

**Goal:** Learn strategies (policies) that maximize long-term cumulative rewards.  

**Examples:** Training AI to play games like Chess or Go, teaching robots to walk, self-driving cars.  

**Key Algorithms:** Markov Decision Process, Q-Learning, Deep Q-Networks (DQN), Policy Gradients, Actor-Critic, PPO, Monte Carlo Methods.  
    `,
    items: [
      { name: "Markov Decision Process (MDP)", slug: "mdp", description: "Mathematical framework for modeling decision making.", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec.", src: "/gifs/lr.gif" },
      { name: "Q-Learning", slug: "q-learning", description: "Model-free RL algorithm to learn optimal action policies.", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec.", src: "/gifs/lr.gif" },
      { name: "Deep Q-Networks (DQN)", slug: "dqn", description: "Combines Q-Learning with deep neural networks.", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec.", src: "/gifs/lr.gif" },
      { name: "Policy Gradients", slug: "policy-gradients", description: "Directly learns the policy function for actions.", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec.", src: "/gifs/lr.gif" },
      { name: "Actor-Critic Methods", slug: "actor-critic", description: "Combines policy and value-based RL methods.", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec.", src: "/gifs/lr.gif" },
      { name: "Proximal Policy Optimization (PPO)", slug: "ppo", description: "Stable and efficient RL algorithm using clipped objectives.", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec.", src: "/gifs/lr.gif" },
      { name: "Monte Carlo Methods", slug: "monte-carlo", description: "Estimates value functions by sampling returns.", body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum auctor felis nec.", src: "/gifs/lr.gif" },
    ],
  },
];
